const AUDIT_ACTIONS = {
  TEMPORARY_DEVICE_EXPIRED: 'TEMPORARY_DEVICE_EXPIRED',
  TEMPORARY_LOCATION_EXPIRED: 'TEMPORARY_LOCATION_EXPIRED',
  BIOMETRIC_ENROLLED: 'BIOMETRIC_ENROLLED',
  BIOMETRIC_AUTH_SUCCESS: 'BIOMETRIC_AUTH_SUCCESS',
  ATTENDANCE_METHOD_SWITCHED: 'ATTENDANCE_METHOD_SWITCHED',
};

module.exports = { AUDIT_ACTIONS };
